### ISSUE TITLE
Checking of imported contract failed if not specified for deployment

### ISSUE THREAD

**Issue by aacoimbra** [onflow/vscode-cadence#319]
## **Problem**

Extension raises error when importing a contract that is not manually deployed but instead automatically deployed in the emulator such as the FlowToken contract.

![image](https://github.com/onflow/vscode-cadence/assets/35254788/503bb996-44d6-4cc2-9a81-d3e84f243b62)

Given the following flow.json file, importing `NonFungibleToken` will work, but importing `FlowToken` will not.
This behavior also occurs for other automatically deployed contracts.

```
{
    "contracts": {
        "FlowToken": {
            "source": "./cadence/contracts/FlowToken.cdc",
            "aliases": {
                "emulator": "0ae53cb6e3f42a79"
            }
        },
        "NonFungibleToken": {
            "source": "./cadence/contracts/NonFungibleToken.cdc"
        },
    },
    "networks": {
        "emulator": "127.0.0.1:3569"
    },
    "accounts": {
        "emulator-account": {
            "address": "f8d6e0586b0a20c7",
            "key": "d6458c0a5d0903987dccbc630e7b8f48975ae55a115baca1f4decce5b78057ed"
        }
    },
    "deployments": {
        "emulator": {
            "emulator-account": [
                "NonFungibleToken"
            ]
        }
    }
}
```

## Steps to Reproduce
Copy flow.json above and create the folder strucure complying with "./cadence/contracts/NonFungibleToken.cdc" and paste the contracts.
Attempt to import `FlowToken` in a .cdc file.

## **Workaround**

Making the following change to flow.json will avoid raising an error when importing, but will unnecessarily deploy the contract to `emulator-account`.

```
    "deployments": {
        "emulator": {
            "emulator-account": [
                "NonFungibleToken",
                "FlowToken"
            ]
        }
    }
```

This issue can be reliably reproduced.
Extension version v1.2.0.
OS: Windows 11

**Comment by sideninja** [comment]
@aacoimbra thanks for reporting this, but this is by design, we intentionally check only the contracts you have in the deployments section, because there might be different contracts deployed for different networks. 
The issue I see tho, is that, obviously one part of the process is broken here. So if I understand you deployed a contract to an account using the "deploy contract" button inside the vscode? and then you had issues importing it?

**Comment by aacoimbra** [comment]
@sideninja Actually I’m not using the extension to deploy contracts or send transactions, I’m doing this using the fcl. 
My goal here is to have the intellisense features of the extension.

**Comment by aacoimbra** [comment]
To be clear, in this case I want to run the emulator with only default contracts, and deploy all my contracts and run transactions with fcl, to simulate exactly how it will be in production. But if I don't specify the contracts for deployment in flow.json, the intellisense features of the extenseion won't work for any contract or transactions I'm creating.

**Comment by sideninja** [comment]
@aacoimbra Unfortunately that's how we know what is that you are importing. Unless you use file path location to the contract, which I don't advise, we can't know which contract your import references unless you specify that in configuration flow.json. There are tools that do that for you like `flow dev`, but otherwise I'm not sure how do you think this could work without it?

**Comment by sideninja** [comment]
Also note that if you use `flow setup` to setup your project you get most of the standard contracts already in the flow.json.

**Comment by sideninja** [comment]
However, the IntelliSense for contracts you defined an alias for (like the FlowToken above) should work without adding them to the deployments section. But you must make sure that contract was actually deployed.

**Comment by jribbink** [comment]
This should be solved by https://github.com/onflow/cadence-tools/pull/224 (pending a new release of the language server and Flow CLI)
